[package]
name = "weather_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
reqwest = { version = "0.12.24", features = ["json", "blocking"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
